# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Page4_a.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
class Ui_MainWindow(object):
    def setupUi(self, MainWindow,a):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 547)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 135, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 230, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 275, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 315, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 365, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 410, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 445, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(140, 95, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(100, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(130, 185, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(94, 230, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(80, 275, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(140, 320, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(130, 366, 55, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(120, 410, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(140, 455, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(440, 100, 191, 241))
        self.label_20.setObjectName("label_20")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow,a)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow,a):
        dbobj=sqlite3.connect("FantasyCricket.db")
        cur=dbobj.cursor()
        if a==0:
            cur.execute("SELECT * FROM Stats WHERE Player='Virat Kohli';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"vk.jpg\"/></p></body></html>"))
        elif a==1:
            cur.execute("SELECT * FROM Stats WHERE Player='MS Dhoni';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"ms.jpg\"/></p></body></html>"))
        elif a==2:
            cur.execute("SELECT * FROM Stats WHERE Player='Rohit';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"ro.jpg\"/></p></body></html>"))
        elif a==3:
            cur.execute("SELECT * FROM Stats WHERE Player='Ashwin';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"ra.jpg\"/></p></body></html>"))
        elif a==4:
            cur.execute("SELECT * FROM Stats WHERE Player='Jadeja';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"rj.jpg\"/></p></body></html>"))
        elif a==5:
            cur.execute("SELECT * FROM Stats WHERE Player='KL Rahul';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"klr.jpg\"/></p></body></html>"))
        elif a==6:
            cur.execute("SELECT * FROM Stats WHERE Player='Raina';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"sr.jpg\"/></p></body></html>"))
        elif a==7:
            cur.execute("SELECT * FROM Stats WHERE Player='Rahane';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"ar.jpg\"/></p></body></html>"))
        elif a==8:
            cur.execute("SELECT * FROM Stats WHERE Player='Dhawan';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"sd.jpg\"/></p></body></html>"))
        elif a==9:
            cur.execute("SELECT * FROM Stats WHERE Player='Pujara';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"cp.jpg\"/></p></body></html>"))
        elif a==10:
            cur.execute("SELECT * FROM Stats WHERE Player='Pandya';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"hp.jpg\"/></p></body></html>"))
        elif a==11:
            cur.execute("SELECT * FROM Stats WHERE Player='Umesh';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"uy.jpg\"/></p></body></html>"))
        elif a==12:
            cur.execute("SELECT * FROM Stats WHERE Player='Bhuvneshwar';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"bk.jpg\"/></p></body></html>"))
        elif a==13:
            cur.execute("SELECT * FROM Stats WHERE Player='Shami';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"sm.jpg\"/></p></body></html>"))
        elif a==14:
            cur.execute("SELECT * FROM Stats WHERE Player='Dinesh Kartick';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"dk.jpg\"/></p></body></html>"))
        elif a==15:
            cur.execute("SELECT * FROM Stats WHERE Player='Bumrah';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"bum.jpg\"/></p></body></html>"))
        elif a==16:
            cur.execute("SELECT * FROM Stats WHERE Player='Kuldeep';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"ky.jpg\"/></p></body></html>"))
        elif a==17:
            cur.execute("SELECT * FROM Stats WHERE Player='Chahal';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"yc.jpg\"/></p></body></html>"))
        elif a==18:
            cur.execute("SELECT * FROM Stats WHERE Player='Kedar Jadhav';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"kj.jpg\"/></p></body></html>"))
        elif a==19:
            cur.execute("SELECT * FROM Stats WHERE Player='Ishant';")
            r=cur.fetchone()
            x0=r[0]
            x1=str(r[1])
            x2=str(r[2])
            x3=str(r[3])
            x4=str(r[4])
            x5=str(r[5])
            x6=r[6]
            x7=str(r[7])
            x8=str(r[8])
            x9=str(r[9])
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket - Players Stats"))
            self.label.setText(_translate("MainWindow", x0))
            self.label_2.setText(_translate("MainWindow", "Matches:"))
            self.label_3.setText(_translate("MainWindow", "Runs:"))
            self.label_4.setText(_translate("MainWindow", "Average:"))
            self.label_5.setText(_translate("MainWindow", "100s:"))
            self.label_6.setText(_translate("MainWindow", "50s:"))
            self.label_7.setText(_translate("MainWindow", "Category:"))
            self.label_8.setText(_translate("MainWindow", "Wickets:"))
            self.label_9.setText(_translate("MainWindow", "5 Wkts:"))
            self.label_10.setText(_translate("MainWindow", "Economy:"))
            self.label_11.setText(_translate("MainWindow", x1))
            self.label_12.setText(_translate("MainWindow", x2))
            self.label_13.setText(_translate("MainWindow", x3))
            self.label_14.setText(_translate("MainWindow", x4))
            self.label_15.setText(_translate("MainWindow", x5))
            self.label_16.setText(_translate("MainWindow", x6))
            self.label_17.setText(_translate("MainWindow", x7))
            self.label_18.setText(_translate("MainWindow", x8))
            self.label_19.setText(_translate("MainWindow", x9))
            self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"is.jpg\"/></p></body></html>"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow,a)
    MainWindow.show()
    sys.exit(app.exec_())

